"use client";

import { useRouter } from "next/navigation";
import { Activity, AlertTriangle, Archive, ChevronDown, ClipboardList, FileSearch, Gauge, LayoutDashboard, ListChecks, Map, MoreHorizontal, Settings, ShieldCheck } from "lucide-react";
import { endDemoSession } from "@/lib/demo-auth";

/**
 * The application sidebar, shared by every page. Moved verbatim out of src/app/page.tsx;
 * the navigation targets are unchanged.
 */
export function Sidebar({ active, setActive }: { active: string; setActive: (value: string) => void }) { const router = useRouter(); const logout = () => { endDemoSession(); router.replace("/login"); }; const items = [{ label: "Dashboard", icon: LayoutDashboard, href: "/dashboard" }, { label: "Projects", icon: ClipboardList, href: "/projects" }, { label: "Risk signals", icon: AlertTriangle, href: "/projects?risk=high" }, { label: "SLA monitoring", icon: ListChecks, href: "/sla" }, { label: "Geospatial view", icon: Map, href: "/gis-check" }]; return <aside className="sidebar"><div className="brand"><span className="brand-mark"><Activity size={17} /></span><span>PAIMANA</span><small>INTELLIGENCE</small></div><button className="workspace-label" onClick={() => router.push("/settings")} aria-label="Open workspace settings">WORKSPACE <ChevronDown size={13} /></button><button className="workspace-name" onClick={() => router.push("/settings")} aria-label="Open National Infrastructure workspace">National Infrastructure <span className="online-dot" /></button><nav><p className="nav-label">MONITORING</p>{items.map(({ label, icon: Icon, href }) => <button key={label} className={active === label ? "nav-item active" : "nav-item"} onClick={() => { setActive(label); router.push(href); }}><Icon size={17} />{label}</button>)}<p className="nav-label second">DOCUMENTS</p>{[{ label: "Document analyzer", icon: FileSearch, href: "/documents" }, { label: "Saved analyses", icon: Archive, href: "/analyses" }].map(({ label, icon: Icon, href }) => <button key={label} className={active === label ? "nav-item active" : "nav-item"} onClick={() => { setActive(label); router.push(href); }}><Icon size={17} />{label}</button>)}<p className="nav-label second">DECISIONS</p>{[{ label: "Interventions", icon: ShieldCheck, href: projectIdHref() }, { label: "Scenario lab", icon: Gauge, href: projectIdHref("#scenario") }].map(({ label, icon: Icon, href }) => <button key={label} className="nav-item" onClick={() => { setActive(label); router.push(href); }}><Icon size={17} />{label}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={() => router.push("/settings")}><Settings size={17} />Workspace settings</button><button className="user-mini" onClick={logout} aria-label="Sign out Ananya Sharma"><span>AS</span><div><strong>Ananya Sharma</strong><small>Sign out</small></div><MoreHorizontal size={16} /></button></div></aside>; }

function projectIdHref(anchor = "") { if (typeof window === "undefined") return anchor ? `/scenario` : "/projects"; const match = window.location.pathname.match(/^\/projects\/([^/]+)/); return match ? `/projects/${match[1]}${anchor}` : anchor ? "/scenario" : "/projects"; }
