"use client";

import { useState } from "react";
import { Activity, AlertTriangle, ArrowLeft, ArrowUpRight, Bell, CalendarDays, Check, ChevronDown, ChevronRight, ClipboardList, Clock3, FileOutput, Gauge, LayoutDashboard, Map, Menu, MoreHorizontal, Search, Settings, ShieldCheck, Sparkles, Target, TrendingDown, TrendingUp, X } from "lucide-react";

const drivers = [{ name: "Land acquisition", value: 34, color: "#c95740" }, { name: "Milestone slippage", value: 26, color: "#d88049" }, { name: "Financial progress gap", value: 17, color: "#bb9840" }, { name: "Pending clearance", value: 13, color: "#74967c" }];
const twins = [{ similarity: "94%", name: "Western Freight Corridor", outcome: "12-month delay", cause: "Land acquisition", sector: "Railways" }, { similarity: "89%", name: "Dedicated Freight Corridor - Phase I", outcome: "8-month delay", cause: "Milestone slippage", sector: "Railways" }, { similarity: "81%", name: "North-South Rail Link", outcome: "6-month delay", cause: "Funding release", sector: "Railways" }];
const interventions = [{ rank: "01", title: "Accelerate Land Acquisition Resolution", why: "Primary contributor to current risk.", impact: "Potential reduction of projected delay by 3-5 months.", confidence: "Based on historical intervention patterns." }, { rank: "02", title: "Review Critical Milestone Dependencies", why: "Three packages share a delayed right-of-way handover.", impact: "Potentially recover 2 months on the critical path.", confidence: "Model confidence: High." }, { rank: "03", title: "Conduct Funding Bottleneck Assessment", why: "Financial progress is 17% below expected trajectory.", impact: "Protect up to Rs 120 Cr from cost escalation.", confidence: "Based on current cash-flow signals." }];

function RiskPill({ children }: { children: React.ReactNode }) { return <span className="risk-pill critical"><i />{children}</span>; }
function Sidebar({ active, setActive }: { active: string; setActive: (value: string) => void }) { const items = [{ label: "Overview", icon: LayoutDashboard }, { label: "Project portfolio", icon: ClipboardList }, { label: "Risk signals", icon: AlertTriangle }, { label: "Geospatial view", icon: Map }]; return <aside className="sidebar"><div className="brand"><span className="brand-mark"><Activity size={17} /></span><span>PAIMANA</span><small>INTELLIGENCE</small></div><div className="workspace-label">WORKSPACE <ChevronDown size={13} /></div><div className="workspace-name">National Infrastructure <span className="online-dot" /></div><nav><p className="nav-label">MONITORING</p>{items.map(({ label, icon: Icon }) => <button key={label} className={active === label ? "nav-item active" : "nav-item"} onClick={() => setActive(label)}><Icon size={17} />{label}{label === "Risk signals" && <b>7</b>}</button>)}<p className="nav-label second">DECISIONS</p>{[{ label: "Interventions", icon: ShieldCheck }, { label: "Scenario lab", icon: Gauge }].map(({ label, icon: Icon }) => <button key={label} className="nav-item" onClick={() => setActive(label)}><Icon size={17} />{label}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings size={17} />Workspace settings</button><div className="user-mini"><span>AS</span><div><strong>Ananya Sharma</strong><small>Portfolio director</small></div><MoreHorizontal size={16} /></div></div></aside>; }

export default function Home() {
  const [active, setActive] = useState("Project intelligence"); const [showSearch, setShowSearch] = useState(false); const [notice, setNotice] = useState(false); const [landStatus, setLandStatus] = useState(34); const [funding, setFunding] = useState(72); const [milestones, setMilestones] = useState(3); const [resources, setResources] = useState(50);
  const scenarioRisk = Math.max(48, Math.round(96 - (landStatus - 34) * .45 - (funding - 72) * .15 - (3 - milestones) * 5 - (resources - 50) * .12)); const scenarioDelay = Math.max(4, Math.round(10 - (landStatus - 34) * .035 - (funding - 72) * .008 - (3 - milestones) * .8 - (resources - 50) * .02)); const scenarioCost = Math.max(180, Math.round(420 - (96 - scenarioRisk) * 5.6));
  return <div className="app-shell"><Sidebar active={active} setActive={setActive} /><main className="main-content"><header className="topbar"><div className="mobile-brand"><Menu size={20} /><strong>PAIMANA</strong></div><div className="breadcrumb"><button className="back-link"><ArrowLeft size={13} /> Portfolio</button> / <strong>PROJECT INTELLIGENCE</strong></div><div className="top-actions"><button className="icon-button search-trigger" onClick={() => setShowSearch(!showSearch)}><Search size={18} /><span>Search projects</span><kbd>Cmd K</kbd></button><button className="period"><CalendarDays size={16} /> Q3 FY 2026 <ChevronDown size={14} /></button><button className="icon-only" onClick={() => setNotice(!notice)} aria-label="Notifications"><Bell size={18} />{notice && <span className="notification-pop">3 new signals</span>}</button><div className="avatar">AS</div></div></header>{showSearch && <div className="search-panel"><Search size={17} /><input autoFocus placeholder="Search projects, regions, signals..." /><button onClick={() => setShowSearch(false)}><X size={16} /></button></div>}
      <div className="detail-wrap"><header className="project-header"><div><div className="eyebrow"><span className="live-dot" /> AI MONITORING ACTIVE</div><h1>Eastern Freight Corridor Expansion</h1><p>Railways <span>•</span> Northern Region <span>•</span> Project ID: EFC-04</p></div><div className="project-header-actions"><span className="updated"><span className="green-dot" /> Updated 12 min ago</span><button className="export-button"><FileOutput size={15} /> Export brief</button></div></header>
        <section className="executive-summary"><div className="summary-name"><span>PROJECT STATUS</span><RiskPill>CRITICAL</RiskPill><small>Last reviewed by portfolio office 03 Sep 2026</small></div><div className="summary-stat score"><span>AI RISK SCORE</span><strong>96 <small>/ 100</small></strong><div className="score-line"><i /></div></div><div className="summary-stat"><span>PREDICTED DELAY</span><strong>8-11 <small>months</small></strong><small>Model estimate</small></div><div className="summary-stat cost"><span>POTENTIAL COST IMPACT</span><strong>Rs 420 <small>Cr</small></strong><small>Model estimate</small></div><div className="summary-confidence"><span>MODEL CONFIDENCE</span><strong>High</strong><small><Check size={12} /> Validated on 17 similar projects</small></div></section>
        <section className="why-section report-section"><div className="report-title"><span className="section-number">01</span><div><span className="eyebrow">EXPLAINABLE RISK ANALYSIS</span><h2>Why is this project at risk?</h2><p>Four factors account for the current risk assessment.</p></div></div><div className="why-grid"><div className="driver-visual">{drivers.map((driver, index) => <div className="driver-item" key={driver.name}><div className="driver-label"><span>0{index + 1}</span><strong>{driver.name}</strong><b>{driver.value}%</b></div><div className="driver-track"><i style={{ width: `${driver.value * 2.35}%`, background: driver.color }} /></div></div>)}<div className="driver-scale"><span>LOW CONTRIBUTION</span><span>HIGH CONTRIBUTION</span></div></div><div className="summary-callout"><div className="callout-mark"><Sparkles size={16} /></div><span className="eyebrow">NATURAL-LANGUAGE EXPLANATION</span><p>The project risk is primarily driven by incomplete land acquisition and repeated slippage across critical milestones. Financial progress has also fallen below the expected trajectory.</p><div className="callout-foot"><span><Target size={13} /> Top contributor</span><b>Land acquisition · 34%</b></div></div></div></section>
        <section className="trajectory-section report-section"><div className="report-title"><span className="section-number">02</span><div><span className="eyebrow">TEMPORAL ANALYSIS</span><h2>Risk trajectory</h2><p>How the model’s assessment changed over time.</p></div><span className="trajectory-legend"><i className="historical" /> Historical <i className="current" /> Current <i className="forecast" /> Predicted</span></div><div className="trajectory-chart"><div className="y-labels"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="trajectory-lines"><div className="grid-lines"><i /><i /><i /><i /><i /></div><svg viewBox="0 0 700 180" preserveAspectRatio="none" aria-label="Risk trajectory chart"><polyline points="0,145 85,137 170,128 255,113 340,98" fill="none" stroke="#73927e" strokeWidth="3" /><polyline points="340,98 430,77 520,55 610,36 700,23" fill="none" stroke="#c95740" strokeWidth="3" strokeDasharray="8 6" /><circle cx="340" cy="98" r="5" fill="#c95740" /><circle cx="700" cy="23" r="5" fill="#c95740" /></svg><div className="trajectory-label current-label">CURRENT<br /><b>96</b></div><div className="trajectory-label forecast-label">PROJECTED PEAK<br /><b>99</b></div><div className="x-labels"><span>Q1 2025</span><span>Q2 2025</span><span>Q3 2025</span><span>Q4 2025</span><span>Q1 2026</span><span>Q2 2026</span></div></div></div></section>
        <section className="twins-section report-section"><div className="report-title"><span className="section-number">03</span><div><span className="eyebrow">PATTERN RECOGNITION</span><h2>Historical project twin</h2><p>Past projects with similar risk signatures and operating context.</p></div></div><div className="twin-table">{twins.map(twin => <div className="twin-row" key={twin.name}><strong className="twin-sim">{twin.similarity}<small>SIMILAR</small></strong><div><strong>{twin.name}</strong><small>{twin.sector}</small></div><div><span>ACTUAL OUTCOME</span><b>{twin.outcome}</b></div><div><span>PRIMARY CAUSE</span><b>{twin.cause}</b></div><ChevronRight size={18} className="row-arrow" /></div>)}</div><div className="twin-insight"><Sparkles size={15} /><strong>12 of 17 similar projects experienced delays greater than 6 months.</strong><span>Pattern confidence: High</span></div></section>
        <section className="interventions-detail report-section"><div className="report-title"><span className="section-number">04</span><div><span className="eyebrow">DECISION SUPPORT</span><h2>Recommended interventions</h2><p>Prioritized actions with a measurable effect on the forecast.</p></div></div><div className="intervention-detail-list">{interventions.map(item => <div className="intervention-detail-row" key={item.rank}><span className="intervention-rank">{item.rank}</span><div className="intervention-main"><strong>{item.title}</strong><span>{item.why}</span></div><div><small>ESTIMATED IMPACT</small><p>{item.impact}</p></div><div><small>CONFIDENCE</small><p className="confidence-text">{item.confidence}</p></div><button aria-label={`Review ${item.title}`}><ArrowUpRight size={16} /></button></div>)}</div></section>
        <section className="scenario-section report-section"><div className="report-title"><span className="section-number">05</span><div><span className="eyebrow">SCENARIO SIMULATOR</span><h2>What if we intervene?</h2><p>Adjust the intervention inputs to explore a modeled outcome.</p></div><span className="estimate-label">MODEL ESTIMATES ONLY</span></div><div className="scenario-grid"><div className="scenario-controls"><div className="control"><label>Land acquisition status <b>{landStatus}% resolved</b></label><input type="range" min="34" max="100" value={landStatus} onChange={e => setLandStatus(Number(e.target.value))} /></div><div className="control"><label>Funding availability <b>{funding}% available</b></label><input type="range" min="50" max="100" value={funding} onChange={e => setFunding(Number(e.target.value))} /></div><div className="control"><label>Delayed milestones <b>{milestones} packages</b></label><input type="range" min="0" max="5" value={milestones} onChange={e => setMilestones(Number(e.target.value))} /></div><div className="control"><label>Resource allocation <b>{resources}% of plan</b></label><input type="range" min="25" max="100" value={resources} onChange={e => setResources(Number(e.target.value))} /></div><div className="simulation-status"><Activity size={14} /> Simulation updates as inputs change</div></div><div className="scenario-results"><div className="scenario-card current"><span>CURRENT TRAJECTORY</span><small>No intervention</small><strong>96</strong><label>RISK SCORE</label><div><b>10 months</b><span>Predicted delay</span></div><div><b>Rs 420 Cr</b><span>Estimated cost impact</span></div></div><div className="scenario-arrow"><ArrowUpRight size={20} /></div><div className="scenario-card intervention"><span>INTERVENTION SCENARIO</span><small>Based on current inputs</small><strong>{scenarioRisk}</strong><label>RISK SCORE</label><div><b>{scenarioDelay} months</b><span>Predicted delay</span></div><div><b>Rs {scenarioCost} Cr</b><span>Estimated cost impact</span></div></div></div></div></section>
        <section className="anomaly-section"><div className="anomaly-icon"><AlertTriangle size={17} /></div><div><span className="eyebrow">DATA ANOMALY / VERIFICATION ALERT</span><h3>Unusual progress pattern detected.</h3><p>Physical progress increased by 18% during the latest reporting cycle while financial expenditure remained relatively unchanged.</p></div><div className="anomaly-status"><span>STATUS</span><strong>Verification recommended</strong><button>Open investigation <ArrowUpRight size={14} /></button></div></section>
        <footer><span><span className="green-dot" /> AI monitoring active</span><span>Data through 03 Sep 2026 · 09:42 IST</span><span>PAIMANA Intelligence v2.4</span></footer>
      </div></main></div>;
}
