"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, AlertTriangle, Archive, ArrowLeft, ArrowUpRight, Bell, BookmarkCheck, CalendarDays, Check, ChevronDown, ChevronRight, ClipboardList, FileOutput, FileSearch, Gauge, LayoutDashboard, Map, Menu, MoreHorizontal, PencilLine, Save, Search, Settings, ShieldCheck, Sparkles, Target, X } from "lucide-react";
import { getProject, getProjectIntelligence, fetchProjectIntelligence, type ProjectIntelligenceResponse, type ProjectRecord, type ProjectRiskInput, type ProjectRiskResponse, type GisScreening } from "@/lib/prediction-api";
import { endDemoSession } from "@/lib/demo-auth";
import DocumentUploadModal from "@/components/documents/DocumentUploadModal";
import { GisScreeningPanel } from "@/components/intelligence/gis-screening-panel";

/**
 * A report input that did not come from the project registry -- today, values a user
 * reviewed on the document analyzer. Coordinates are optional: when present the GIS
 * screening stage runs against them.
 */
export type ReportDraft = { label: string; source: string; input: ProjectRiskInput; latitude?: number | null; longitude?: number | null; /** Set when the draft is a saved analysis being viewed again. */ savedAt?: string | null };

const drivers = [{ name: "Land acquisition", value: 34, color: "#c95740" }, { name: "Milestone slippage", value: 26, color: "#d88049" }, { name: "Financial progress gap", value: 17, color: "#bb9840" }, { name: "Pending clearance", value: 13, color: "#74967c" }];

const interventions = [{ rank: "01", title: "Accelerate Land Acquisition Resolution", why: "Primary contributor to current risk.", impact: "Potential reduction of projected delay by 3-5 months.", confidence: "Based on historical intervention patterns." }, { rank: "02", title: "Review Critical Milestone Dependencies", why: "Three packages share a delayed right-of-way handover.", impact: "Potentially recover 2 months on the critical path.", confidence: "Model confidence: High." }, { rank: "03", title: "Conduct Funding Bottleneck Assessment", why: "Financial progress is 17% below expected trajectory.", impact: "Protect up to Rs 120 Cr from cost escalation.", confidence: "Based on current cash-flow signals." }];

function RiskPill({ children }: { children: React.ReactNode }) { return <span className="risk-pill critical"><i />{children}</span>; }
export function Sidebar({ active, setActive }: { active: string; setActive: (value: string) => void }) { const router = useRouter(); const logout = () => { endDemoSession(); router.replace("/login"); }; const items = [{ label: "Dashboard", icon: LayoutDashboard, href: "/dashboard" }, { label: "Risk signals", icon: AlertTriangle, href: "/dashboard?risk=high" }, { label: "Geospatial view", icon: Map, href: "/gis-check" }]; return <aside className="sidebar"><div className="brand"><span className="brand-mark"><Activity size={17} /></span><span>PAIMANA</span><small>INTELLIGENCE</small></div><button className="workspace-label" onClick={() => router.push("/settings")} aria-label="Open workspace settings">WORKSPACE <ChevronDown size={13} /></button><button className="workspace-name" onClick={() => router.push("/settings")} aria-label="Open National Infrastructure workspace">National Infrastructure <span className="online-dot" /></button><nav><p className="nav-label">MONITORING</p>{items.map(({ label, icon: Icon, href }) => <button key={label} className={active === label ? "nav-item active" : "nav-item"} onClick={() => { setActive(label); router.push(href); }}><Icon size={17} />{label}{label === "Risk signals" && <b>7</b>}</button>)}<p className="nav-label second">DOCUMENTS</p>{[{ label: "Document analyzer", icon: FileSearch, href: "/documents" }, { label: "Saved analyses", icon: Archive, href: "/analyses" }].map(({ label, icon: Icon, href }) => <button key={label} className={active === label ? "nav-item active" : "nav-item"} onClick={() => { setActive(label); router.push(href); }}><Icon size={17} />{label}</button>)}<p className="nav-label second">DECISIONS</p>{[{ label: "Interventions", icon: ShieldCheck, href: projectIdHref() }, { label: "Scenario lab", icon: Gauge, href: projectIdHref("#scenario") }].map(({ label, icon: Icon, href }) => <button key={label} className="nav-item" onClick={() => { setActive(label); router.push(href); }}><Icon size={17} />{label}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={() => router.push("/settings")}><Settings size={17} />Workspace settings</button><button className="user-mini" onClick={logout} aria-label="Sign out Ananya Sharma"><span>AS</span><div><strong>Ananya Sharma</strong><small>Sign out</small></div><MoreHorizontal size={16} /></button></div></aside>; }

function projectIdHref(anchor = "") { if (typeof window === "undefined") return anchor ? `/scenario` : "/dashboard"; const match = window.location.pathname.match(/^\/projects\/([^/]+)/); return match ? `/projects/${match[1]}${anchor}` : anchor ? "/scenario" : "/dashboard"; }

/**
 * `precomputed`: a report that was already produced (a saved analysis) -- rendered as-is, the
 * pipeline is not re-run. `onSave`: when given, the header shows a Save control; the parent
 * owns what "saving" means, Home only hands over the name and the result it is showing.
 */
export default function Home({ projectId, draft, precomputed, onEditDraft, onSave, onBack }: { projectId?: string; draft?: ReportDraft; precomputed?: ProjectIntelligenceResponse; onEditDraft?: () => void; onSave?: (name: string, result: ProjectIntelligenceResponse) => Promise<void>; onBack?: { label: string; onClick: () => void } } = {}) {
  const router = useRouter(); const [active, setActive] = useState(precomputed ? "Saved analyses" : draft ? "Document analyzer" : "Project intelligence"); const [showSearch, setShowSearch] = useState(false); const [searchQuery, setSearchQuery] = useState(""); const [notice, setNotice] = useState(false); const [showDocuments, setShowDocuments] = useState(false); const [landStatus, setLandStatus] = useState(34); const [funding, setFunding] = useState(72); const [milestones, setMilestones] = useState(3); const [resources, setResources] = useState(50); const [prediction, setPrediction] = useState<ProjectRiskResponse | null>(null); const [predictionError, setPredictionError] = useState<string | null>(null); const [isPredicting, setIsPredicting] = useState(false); const [project, setProject] = useState<ProjectRecord | null>(null); const [intelligence, setIntelligence] = useState<ProjectIntelligenceResponse | null>(null); const [isLoadingProject, setIsLoadingProject] = useState(Boolean(projectId)); const [projectError, setProjectError] = useState<string | null>(null); const [selectedHistorical, setSelectedHistorical] = useState<ProjectIntelligenceResponse["similar_projects"][number] | null>(null); const [selectedIntervention, setSelectedIntervention] = useState<(typeof interventions)[number] | null>(null); const [gisNotice, setGisNotice] = useState<string | null>(null); const [saveName, setSaveName] = useState(draft?.label ?? ""); const [saveStatus, setSaveStatus] = useState<"idle" | "saving" | "saved" | "error">("idle"); const [saveError, setSaveError] = useState<string | null>(null); const [investigationOpen, setInvestigationOpen] = useState(false);
  const [gisScreening, setGisScreening] = useState<GisScreening | null>(null);
  // Draft path: the reviewed document values go through the same single-call pipeline the
  // registry path uses. Coordinates are attempted first; if the spatial stage fails the
  // run is repeated without them so a GIS outage cannot hide a risk analysis that works.
  const runDraftAnalysis = async () => { if (!draft) return; setIsPredicting(true); setPredictionError(null); setGisNotice(null); const hasLocation = draft.latitude != null && draft.longitude != null; try { let result: ProjectIntelligenceResponse; try { result = await fetchProjectIntelligence(hasLocation ? { ...draft.input, latitude: draft.latitude, longitude: draft.longitude, buffer_meters: 2000 } : draft.input); } catch (error) { if (!hasLocation) throw error; result = await fetchProjectIntelligence(draft.input); setGisNotice(`GIS screening could not be completed: ${error instanceof Error ? error.message : "spatial engine unavailable"}`); } setIntelligence(result); setPrediction({ project_risk: result.project_risk, top_risk_factors: result.top_risk_factors, summary: result.risk_summary }); setGisScreening(result.gis_screening ?? null); setSaveStatus("idle"); setSaveError(null); } catch (error) { setPredictionError(error instanceof Error ? error.message : "Unable to reach prediction service"); } finally { setIsPredicting(false); } };
  // Saving hands the exact result on screen to the parent; "saved" then locks the control until a new result exists, so one result cannot be stored twice.
  const saveAnalysis = async () => { if (!onSave || !intelligence || saveStatus === "saving" || saveStatus === "saved") return; const name = saveName.trim(); if (!name) { setSaveError("Give the analysis a name before saving"); setSaveStatus("error"); return; } setSaveStatus("saving"); setSaveError(null); try { await onSave(name, intelligence); setSaveStatus("saved"); } catch (error) { setSaveStatus("error"); setSaveError(error instanceof Error ? error.message : "Saving the analysis failed"); } };
  const runProjectAnalysis = async (selectedProject: ProjectRecord | null = project) => { if (!projectId || !selectedProject) return; const { project_id: selectedProjectId, ...selectedInput } = selectedProject; void selectedProjectId; setIsPredicting(true); setPredictionError(null); try { const result = await getProjectIntelligence(projectId, selectedInput); setIntelligence(result); setPrediction({ project_risk: result.project_risk, top_risk_factors: result.top_risk_factors, summary: result.risk_summary }); setGisScreening(result.gis_screening ?? null); } catch (error) { setPredictionError(error instanceof Error ? error.message : "Unable to reach prediction service"); } finally { setIsPredicting(false); } };
  useEffect(() => { if (!projectId) return; let cancelled = false; const loadProject = async () => { try { const record = await getProject(projectId); if (cancelled) return; setProject(record); setProjectError(null); setPrediction(null); setIntelligence(null); setLandStatus(record.land_acquisition_pending ? 34 : 100); setFunding(record.funding_issue ? 72 : 100); setMilestones(record.milestones_delayed); setResources(50); await runProjectAnalysis(record); } catch (error) { if (!cancelled) setProjectError(error instanceof Error ? error.message : "Unable to load project"); } finally { if (!cancelled) setIsLoadingProject(false); } }; void loadProject(); return () => { cancelled = true; }; }, [projectId]);
  useEffect(() => { if (!draft) return; const loadDraft = async () => { setPrediction(null); setIntelligence(null); setGisScreening(null); setSaveStatus("idle"); setSaveError(null); setLandStatus(draft.input.land_acquisition_pending ? 34 : 100); setFunding(draft.input.funding_issue ? 72 : 100); setMilestones(Math.min(5, draft.input.milestones_delayed)); setResources(50); if (precomputed) { setIntelligence(precomputed); setPrediction({ project_risk: precomputed.project_risk, top_risk_factors: precomputed.top_risk_factors, summary: precomputed.risk_summary }); setGisScreening(precomputed.gis_screening ?? null); return; } await runDraftAnalysis(); }; void loadDraft(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [draft, precomputed]);
  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") { setShowSearch(false); setNotice(false); setSelectedHistorical(null); setSelectedIntervention(null); setInvestigationOpen(false); } }; window.addEventListener("keydown", closeOnEscape); return () => window.removeEventListener("keydown", closeOnEscape); }, []);
  const exportBrief = () => { const text = [`PAIMANA PROJECT INTELLIGENCE`, `Project: ${reportTitle}`, `Source: ${draft ? draft.source : "Project registry"}`, `Sector: ${reportInput?.sector ?? "N/A"}`, `State: ${reportInput?.state ?? "N/A"}`, `Risk: ${risk?.risk_percentage ?? "N/A"}/100 (${risk?.risk_level ?? "N/A"})`, `Confidence: ${risk?.model_confidence ?? "N/A"}`, `Explanation: ${prediction?.summary ?? "N/A"}`, `Historical evidence: ${intelligence?.historical_summary ?? "N/A"}`].join("\n"); const url = URL.createObjectURL(new Blob([text], { type: "text/plain" })); const link = document.createElement("a"); link.href = url; link.download = `${(project?.project_id ?? draft?.label ?? "project").replace(/[^\w-]+/g, "_")}-intelligence.txt`; link.click(); URL.revokeObjectURL(url); };
  const reportInput: ProjectRiskInput | null = project ?? draft?.input ?? null;
  const reportTitle = project?.project_id ?? projectId ?? draft?.label ?? "No project selected";
  const risk = intelligence?.project_risk ?? prediction?.project_risk;
  const factors = intelligence?.top_risk_factors ?? prediction?.top_risk_factors ?? [];
  // Rule-based recommendations from the backend when the pipeline returned them; the static list is only a layout placeholder until then.
  const interventionRows = intelligence?.interventions?.length ? intelligence.interventions.map(item => ({ rank: String(item.rank).padStart(2, "0"), title: item.title, why: item.rationale, impact: item.expected_impact, confidence: `${item.urgency} urgency · ${item.evidence_source}` })) : interventions;
  const runAnalysis = () => projectId ? runProjectAnalysis() : runDraftAnalysis();
  const scenarioRisk = Math.max(48, Math.round(96 - (landStatus - 34) * .45 - (funding - 72) * .15 - (3 - milestones) * 5 - (resources - 50) * .12)); const scenarioDelay = Math.max(4, Math.round(10 - (landStatus - 34) * .035 - (funding - 72) * .008 - (3 - milestones) * .8 - (resources - 50) * .02)); const scenarioCost = Math.max(180, Math.round(420 - (96 - scenarioRisk) * 5.6));
  // No registry project and no reviewed draft: say so, rather than scoring a made-up project.
  if (!projectId && !draft) return <div className="app-shell"><Sidebar active={active} setActive={setActive} /><main className="main-content"><header className="topbar"><div className="mobile-brand"><Menu size={20} /><strong>PAIMANA</strong></div><div className="breadcrumb"><strong>PROJECT INTELLIGENCE</strong></div></header><div className="content-wrap"><header className="intro"><div><span className="eyebrow"><ClipboardList size={13} /> PROJECT INTELLIGENCE</span><h1>Project intelligence</h1><p>Open a project record or analyse a project document to generate a report.</p></div></header><section className="signal-panel state-page-panel"><div className="signal-icon"><ClipboardList size={17} /></div><span className="eyebrow">PROJECT REQUIRED</span><h3>No project selected.</h3><p>Reports are generated from a project in the registry or from values reviewed on the document analyzer. Nothing is scored until one of those is chosen.</p><div className="state-page-actions"><button className="dark-button" onClick={() => router.push("/dashboard")}>Choose a project <ArrowUpRight size={14} /></button><button className="export-button" onClick={() => router.push("/documents")}><FileSearch size={15} /> Analyse a document</button></div></section></div></main></div>;
  return <div className="app-shell"><Sidebar active={active} setActive={setActive} /><main className="main-content"><header className="topbar"><div className="mobile-brand"><Menu size={20} /><strong>PAIMANA</strong></div><div className="breadcrumb">{onBack && <><button className="back-link" onClick={onBack.onClick}><ArrowLeft size={13} /> {onBack.label}</button> / </>}<strong>PROJECT INTELLIGENCE</strong></div><div className="top-actions"><button className="icon-button search-trigger" onClick={() => setShowSearch(!showSearch)} aria-expanded={showSearch}><Search size={18} /><span>Search projects</span><kbd>Cmd K</kbd></button><button className="period" aria-label="Current reporting period"><CalendarDays size={16} /> Q3 FY 2026 <ChevronDown size={14} /></button><button className="icon-only" onClick={() => setNotice(!notice)} aria-label="Notifications" aria-expanded={notice}><Bell size={18} />{notice && <span className="notification-pop" role="status">3 new signals · Review risk signals</span>}</button><div className="avatar" aria-label="Signed in as Ananya Sharma">AS</div></div></header>{showSearch && <div className="search-panel" role="search"><Search size={17} /><input autoFocus value={searchQuery} onChange={event => setSearchQuery(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && searchQuery.trim()) router.push(`/dashboard?search=${encodeURIComponent(searchQuery.trim())}`); }} placeholder="Search projects, regions, signals..." aria-label="Search projects" /><button onClick={() => { setShowSearch(false); setSearchQuery(""); }} aria-label="Close search"><X size={16} /></button>{searchQuery && <button className="search-result-link" onClick={() => router.push(`/dashboard?search=${encodeURIComponent(searchQuery.trim())}`)}>Search dashboard for “{searchQuery}”</button>}</div>}
      <div className="detail-wrap"><header className="project-header"><div><div className="eyebrow"><span className="live-dot" /> AI MONITORING ACTIVE</div><h1>{reportTitle}</h1><p>{reportInput?.sector ?? "Data unavailable"} <span>•</span> {reportInput?.state ?? "Data unavailable"} <span>•</span> {draft ? `Source: ${draft.source}` : `Project ID: ${project?.project_id ?? projectId ?? "N/A"}`}</p></div><div className="project-header-actions"><span className="updated"><span className="green-dot" /> {draft?.savedAt ? `Saved ${new Date(draft.savedAt).toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}` : draft ? "Values reviewed from document" : "Live project data"}</span>{draft && onEditDraft && <button className="export-button" onClick={onEditDraft}><PencilLine size={15} /> Edit values</button>}{projectId && <button className="export-button" onClick={() => setShowDocuments(true)} disabled={!project}><FileOutput size={15} /> Documents</button>}{!precomputed && <button className="predict-button" onClick={runAnalysis} disabled={isPredicting || isLoadingProject || (Boolean(projectId) && !project)}><Activity size={15} /> {isPredicting ? "Analyzing..." : "Run AI analysis"}</button>}<button className="export-button" onClick={exportBrief} disabled={!prediction} aria-label="Export project intelligence brief"><FileOutput size={15} /> Export brief</button></div></header>
        {onSave && draft && <div className={`save-control${saveStatus === "saved" ? " saved" : ""}`}><label htmlFor="analysis-name"><span className="eyebrow">SAVE THIS ANALYSIS</span><input id="analysis-name" value={saveName} onChange={event => { setSaveName(event.target.value); if (saveStatus === "error") { setSaveStatus("idle"); setSaveError(null); } }} placeholder="Analysis name" disabled={saveStatus === "saving" || saveStatus === "saved"} aria-label="Analysis name" /></label><button className="dark-button" onClick={saveAnalysis} disabled={!intelligence || saveStatus === "saving" || saveStatus === "saved"}>{saveStatus === "saved" ? <><BookmarkCheck size={14} /> Saved</> : saveStatus === "saving" ? "Saving..." : <><Save size={14} /> Save analysis</>}</button><small>{saveStatus === "saved" ? <><Check size={12} /> Saved to your analyses. Re-run the analysis to save a new result.</> : saveStatus === "error" && saveError ? <span className="save-error"><AlertTriangle size={12} /> {saveError}</span> : !intelligence ? "Available once the analysis has run." : "Stores the confirmed values and this report -- not the PDF."}</small></div>}
        {isLoadingProject && <div className="prediction-hint"><Sparkles size={14} /> Loading project data...</div>}
        {projectError && <div className="prediction-error" role="alert"><AlertTriangle size={15} /> {projectError} <button onClick={() => window.location.reload()}>Retry</button></div>}
        {predictionError && <div className="prediction-error" role="alert"><AlertTriangle size={15} /> {predictionError} <button onClick={runAnalysis}>Retry</button></div>}
        {gisNotice && <div className="prediction-error" role="alert"><AlertTriangle size={15} /> {gisNotice}</div>}
        {!isLoadingProject && !projectError && !prediction && !predictionError && <div className="prediction-hint"><Sparkles size={14} /> Live model output will appear here. Run AI analysis to score this project.</div>}
        <section className="executive-summary"><div className="summary-name"><span>PROJECT STATUS</span><RiskPill>{risk?.risk_level ?? "NOT ANALYZED"}</RiskPill><small>{prediction ? "Model result generated just now" : "Awaiting model analysis"}</small></div><div className="summary-stat score"><span>AI RISK SCORE</span><strong>{risk?.risk_percentage ?? "--"} <small>/ 100</small></strong><div className="score-line"><i style={{ width: `${risk?.risk_percentage ?? 0}%` }} /></div></div><div className="summary-stat"><span>PREDICTED DELAY</span><strong>{risk ? (risk.risk_percentage > 80 ? "8-11" : risk.risk_percentage > 60 ? "5-8" : "2-4") : "--"} <small>months</small></strong><small>Model estimate</small></div><div className="summary-stat cost"><span>POTENTIAL COST IMPACT</span><strong>{risk ? `Rs ${Math.max(120, Math.round(risk.risk_percentage * 4.35))}` : "--"} <small>Cr</small></strong><small>Model estimate</small></div><div className="summary-confidence"><span>MODEL CONFIDENCE</span><strong>{risk?.model_confidence ?? "--"}</strong><small><Check size={12} /> {risk?.confidence_basis ?? "Run analysis to validate"}</small></div></section>
        <section className="why-section report-section"><div className="report-title"><span className="section-number">01</span><div><span className="eyebrow">EXPLAINABLE RISK ANALYSIS</span><h2>Why is this project at risk?</h2><p>{prediction ? "The model’s top contributing factors for this project." : "Run the model to reveal the factors behind this project’s risk."}</p></div></div><div className="why-grid"><div className="driver-visual">{(factors.length ? factors : drivers.map(driver => ({ factor: driver.name.toLowerCase().replaceAll(" ", "_"), importance: driver.value / 100, impact: "increases_risk", description: "Awaiting model explanation." }))).map((factor, index) => <div className="driver-item" key={factor.factor}><div className="driver-label"><span>0{index + 1}</span><strong>{factor.factor.replaceAll("_", " ")}</strong><b>{Math.round(factor.importance * 100)}%</b></div><div className="driver-track"><i style={{ width: `${Math.max(5, factor.importance * 100)}%`, background: factor.impact === "reduces_risk" ? "#74967c" : index === 0 ? "#c95740" : "#d88049" }} /></div></div>)}<div className="driver-scale"><span>LOW CONTRIBUTION</span><span>HIGH CONTRIBUTION</span></div></div><div className="summary-callout"><div className="callout-mark"><Sparkles size={16} /></div><span className="eyebrow">NATURAL-LANGUAGE EXPLANATION</span><p>{prediction?.summary ?? "The model explanation will be summarized here after analysis. Outputs are generated from the saved XGBoost model and SHAP contributions."}</p><div className="callout-foot"><span><Target size={13} /> {factors[0]?.impact === "reduces_risk" ? "Risk-reducing factor" : "Top contributor"}</span><b>{factors[0] ? `${factors[0].factor.replaceAll("_", " ")} · ${Math.round(factors[0].importance * 100)}%` : "Awaiting analysis"}</b></div></div></div></section>
        <section className="trajectory-section report-section"><div className="report-title"><span className="section-number">02</span><div><span className="eyebrow">TEMPORAL ANALYSIS</span><h2>Risk trajectory</h2><p>How the model’s assessment changed over time.</p></div><span className="trajectory-legend"><i className="historical" /> Historical <i className="current" /> Current <i className="forecast" /> Predicted</span></div><div className="trajectory-chart"><div className="y-labels"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="trajectory-lines"><div className="grid-lines"><i /><i /><i /><i /><i /></div><svg viewBox="0 0 700 180" preserveAspectRatio="none" aria-label="Risk trajectory chart"><polyline points="0,145 85,137 170,128 255,113 340,98" fill="none" stroke="#73927e" strokeWidth="3" /><polyline points="340,98 430,77 520,55 610,36 700,23" fill="none" stroke="#c95740" strokeWidth="3" strokeDasharray="8 6" /><circle cx="340" cy="98" r="5" fill="#c95740" /><circle cx="700" cy="23" r="5" fill="#c95740" /></svg><div className="trajectory-label current-label">CURRENT<br /><b>96</b></div><div className="trajectory-label forecast-label">PROJECTED PEAK<br /><b>99</b></div><div className="x-labels"><span>Q1 2025</span><span>Q2 2025</span><span>Q3 2025</span><span>Q4 2025</span><span>Q1 2026</span><span>Q2 2026</span></div></div></div></section>
        <section className="twins-section report-section"><div className="report-title"><span className="section-number">03</span><div><span className="eyebrow">PATTERN RECOGNITION</span><h2>Historical project twin</h2><p>{intelligence ? "Past projects with similar risk signatures and operating context." : "Run AI analysis to find historically similar projects."}</p></div></div><div className="twin-table">{intelligence ? intelligence.similar_projects.map(match =>         <div className="twin-row" key={match.project_id} role="button" tabIndex={0} onClick={() => setSelectedHistorical(match)} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") setSelectedHistorical(match); }}><strong className="twin-sim">{Math.round(match.similarity_score)}%<small>SIMILAR</small></strong><div><strong>{match.project_id}</strong><small>{match.sector} · {match.state}</small></div><div><span>ACTUAL OUTCOME</span><b>{match.actual_delay_months > 0 ? `${match.actual_delay_months}-month delay` : "Delivered within plan"}</b></div><div><span>PRIMARY CAUSE</span><b>{match.primary_delay_cause}</b></div><ChevronRight size={18} className="row-arrow" /></div>) : <div className="twin-row" style={{ justifyContent: "center", color: "#9aa49e", fontSize: "11px", padding: "28px 0" }}>Awaiting analysis</div>}</div>{intelligence ? <div className="twin-insight"><Sparkles size={15} /><strong>{intelligence.historical_summary}</strong><span>Pattern confidence: {intelligence.historical_evidence.significant_delay_percentage >= 70 ? "High" : intelligence.historical_evidence.significant_delay_percentage >= 40 ? "Medium" : "Low"}</span></div> : null}</section>
        <section className="interventions-detail report-section"><div className="report-title"><span className="section-number">04</span><div><span className="eyebrow">DECISION SUPPORT</span><h2>Recommended interventions</h2><p>Prioritized actions with a measurable effect on the forecast.</p></div></div><div className="intervention-detail-list">{interventionRows.map(item => <div className="intervention-detail-row" key={item.rank}><span className="intervention-rank">{item.rank}</span><div className="intervention-main"><strong>{item.title}</strong><span>{item.why}</span></div><div><small>ESTIMATED IMPACT</small><p>{item.impact}</p></div><div><small>CONFIDENCE</small><p className="confidence-text">{item.confidence}</p></div>        <button aria-label={`Review ${item.title}`} onClick={() => setSelectedIntervention(item)}><ArrowUpRight size={16} /></button></div>)}</div></section>
        <section id="scenario" className="scenario-section report-section"><div className="report-title"><span className="section-number">05</span><div><span className="eyebrow">SCENARIO SIMULATOR</span><h2>What if we intervene?</h2><p>Adjust the intervention inputs to explore a modeled outcome.</p></div><span className="estimate-label">MODEL ESTIMATES ONLY</span></div><div className="scenario-grid"><div className="scenario-controls"><div className="control"><label>Land acquisition status <b>{landStatus}% resolved</b></label><input type="range" min="34" max="100" value={landStatus} onChange={e => setLandStatus(Number(e.target.value))} /></div><div className="control"><label>Funding availability <b>{funding}% available</b></label><input type="range" min="50" max="100" value={funding} onChange={e => setFunding(Number(e.target.value))} /></div><div className="control"><label>Delayed milestones <b>{milestones} packages</b></label><input type="range" min="0" max="5" value={milestones} onChange={e => setMilestones(Number(e.target.value))} /></div><div className="control"><label>Resource allocation <b>{resources}% of plan</b></label><input type="range" min="25" max="100" value={resources} onChange={e => setResources(Number(e.target.value))} /></div><div className="simulation-status"><Activity size={14} /> Simulation updates as inputs change</div></div><div className="scenario-results"><div className="scenario-card current"><span>CURRENT TRAJECTORY</span><small>No intervention</small><strong>96</strong><label>RISK SCORE</label><div><b>10 months</b><span>Predicted delay</span></div><div><b>Rs 420 Cr</b><span>Estimated cost impact</span></div></div><div className="scenario-arrow"><ArrowUpRight size={20} /></div><div className="scenario-card intervention"><span>INTERVENTION SCENARIO</span><small>Based on current inputs</small><strong>{scenarioRisk}</strong><label>RISK SCORE</label><div><b>{scenarioDelay} months</b><span>Predicted delay</span></div><div><b>Rs {scenarioCost} Cr</b><span>Estimated cost impact</span></div></div></div></div></section>
        <section className="anomaly-section"><div className="anomaly-icon"><AlertTriangle size={17} /></div><div><span className="eyebrow">DATA ANOMALY / VERIFICATION ALERT</span><h3>Unusual progress pattern detected.</h3><p>Physical progress increased by 18% during the latest reporting cycle while financial expenditure remained relatively unchanged.</p></div><div className="anomaly-status"><span>STATUS</span><strong>Verification recommended</strong>        <button onClick={() => setInvestigationOpen(true)}>Open investigation <ArrowUpRight size={14} /></button></div></section>
        {selectedHistorical && <div className="state-panel" role="dialog" aria-modal="true" aria-labelledby="historical-title"><button className="state-close" onClick={() => setSelectedHistorical(null)} aria-label="Close historical project details"><X size={16} /></button><span className="eyebrow">HISTORICAL PROJECT RECORD</span><h3 id="historical-title">{selectedHistorical.project_id}</h3><p>{selectedHistorical.sector} · {selectedHistorical.state}</p><div className="state-grid"><span>SIMILARITY <b>{Math.round(selectedHistorical.similarity_score)}%</b></span><span>ACTUAL DELAY <b>{selectedHistorical.actual_delay_months} months</b></span><span>COST OVERRUN <b>{selectedHistorical.actual_cost_overrun_percentage}%</b></span><span>PRIMARY CAUSE <b>{selectedHistorical.primary_delay_cause}</b></span></div><small>This is historical evidence and is not an editable current project.</small></div>}
        {selectedIntervention && <div className="state-panel" role="dialog" aria-modal="true" aria-labelledby="intervention-title"><button className="state-close" onClick={() => setSelectedIntervention(null)} aria-label="Close intervention details"><X size={16} /></button><span className="eyebrow">INTERVENTION DETAIL</span><h3 id="intervention-title">{selectedIntervention.title}</h3><p>{selectedIntervention.why}</p><div className="state-grid"><span>ESTIMATED IMPACT <b>{selectedIntervention.impact}</b></span><span>CONFIDENCE <b>{selectedIntervention.confidence}</b></span></div><small>Review uses the available project intelligence context; no additional prediction is generated here.</small></div>}
        {investigationOpen && <div className="state-panel" role="status"><button className="state-close" onClick={() => setInvestigationOpen(false)} aria-label="Close investigation status"><X size={16} /></button><span className="eyebrow">VERIFICATION / INVESTIGATION</span><h3>Investigation workflow unavailable</h3><p>No investigation backend is connected yet. Record this alert for manual verification of the reported progress change.</p><button className="dark-button" onClick={() => setInvestigationOpen(false)}>Acknowledge</button></div>}
        {showDocuments && projectId && project && <DocumentUploadModal isOpen={showDocuments} onClose={() => setShowDocuments(false)} projectId={projectId} projectName={`${project.sector} · ${project.state}`} />}
        <GisScreeningPanel screening={gisScreening} projectId={project?.project_id ?? projectId} />
        <footer><span><span className="green-dot" /> AI monitoring active</span><span>Data through 03 Sep 2026 · 09:42 IST</span><span>PAIMANA Intelligence v2.4</span></footer>
      </div></main></div>;
}
